### ISSUE TITLE
返品対応

### ISSUE THREAD

**Issue by almex-h-hiranishi** [mn-honda/Usen-Studios#110]

**Comment by mm-okuda** [comment]
`public static function sale_month_list($year) {
        $origin_data = Sale::whereYear('created_at', $year)->orderBy('created_at')->get()->groupBy(function ($row) {
            return $row->created_at->format('m');
        })->map(function ($month) {
            $return_money = $month->delivery->where("is_deliveried", "!=", "3")->sum('amount');
            return $month->sum('amount')-$return_money;
        });
        $sale_list = [];
        for ( $i = 1; $i <= 12; $i++ ) {
            $origin_index = $i;
            if ( $i < 10 ) {
                $origin_index = "0{$i}";
            }
            if ( isset($origin_data[$origin_index]) ) {
                $sale_list[$i] = $origin_data[$origin_index];
            } else {
                $sale_list[$i] = 0;
            }
        }
        return $sale_list;
    }`
