### ISSUE TITLE
web.phpの追加編集

### ISSUE THREAD

**Issue by k-sasaki7345** [mn-honda/Usen-Studios#22]

**Comment by mm-okuda** [comment]
商品登録ページ
Route::get('/admin/product_register', function(){
    return view('admin.product_register');
}

**Comment by almex-h-hiranishi** [comment]
カート画面等々いったん
```php
Route::get('/cart', [CartController::class, 'index'])->middleware('auth');
Route::post('/cart/update', [CartController::class, 'update'])->middleware('auth');
Route::post('/cart/delete/{id}', [CartController::class, 'delete'])->middleware('auth');
Route::get('/sale/confirm', [SaleController::class, 'index'])->middleware('auth');
Route::get('/sale/complete', [SaleController::class, 'complete'])->middleware('auth');
```

**Comment by mm-okuda** [comment]
管理者画面
Route::get('admin/product_register', function(){
    return view('admin.product_register');
})->middleware('auth');
Route::get('admin/stock_list', function(){
    return view('admin.stock_list');
})->middleware('auth');
Route::get('admin/purchase_register', function(){
    return view('admin.purchase_register');
})->middleware('auth');
Route::get('admin/purchase_list', function(){
    return view('admin.purchase_list');
})->middleware('auth');
Route::post('admin/product_register', [AdminController::class, 'product_register'])->middleware('auth');
Route::post('admin/purchase_register', [AdminController::class, 'purchase_register'])->middleware('auth');

**Comment by k-sasaki7345** [comment]
ルーティング追加しました。

**Comment by mm-okuda** [comment]
use App\Http\Controllers\AdminController;

Route::get('admin/purchase_register', function(){
    return view('admin.purchase_register');
})->middleware('auth');
を消して
Route::get('admin/purchase_register', [AdminController::class, 'purchase_product']);
追加

**Comment by mm-okuda** [comment]
私の部分丸ごとこれに変えてほしいです🙇‍♀️
Route::get('admin/product_register', function(){
    return view('admin.product_register');
})->middleware('auth');
Route::get('admin/stock_list', [adminController::class, 'stock_list'])->middleware('auth');
Route::get('admin/purchase_register', [AdminController::class, 'purchase_product'])->middleware('auth');
Route::get('admin/purchase_list', [adminController::class, 'purchase_list'])->middleware('auth');
Route::post('admin/product_register', [AdminController::class, 'product_register'])->middleware('auth');
Route::post('admin/purchase_register', [AdminController::class, 'purchase_register'])->middleware('auth');

**Comment by mm-okuda** [comment]
Route::get('admin/product_register', [AdminController::class, 'product'])->middleware('auth');
Route::get('admin/stock_list', [adminController::class, 'stock_list'])->middleware('auth');
Route::get('admin/purchase_register', [AdminController::class, 'purchase_product'])->middleware('auth');
Route::get('admin/purchase_list', [adminController::class, 'purchase_list'])->middleware('auth');
Route::post('admin/product_register', [AdminController::class, 'product_register'])->middleware('auth');
Route::post('admin/purchase_register', [AdminController::class, 'purchase_register'])->middleware('auth');
何度もごめんなさい、これに変更お願いします。

**Comment by almex-h-hiranishi** [comment]
平西ルーティング変更
```php
Route::get('/cart', [CartController::class, 'index'])->middleware('auth');
Route::post('/cart/add', [CartController::class, 'index'])->middleware('auth');
Route::post('/cart/update', [CartController::class, 'update'])->middleware('auth');
Route::post('/cart/delete/{id}', [CartController::class, 'delete'])->middleware('auth');
Route::get('/sale/confirm', [SaleController::class, 'confirm'])->middleware('auth');
Route::get('/sale/registration_credit', [SaleController::class, 'registration_credit'])->middleware('auth');
Route::get('/sale/complete', [SaleController::class, 'complete'])->middleware('auth');
```

**Comment by almex-h-hiranishi** [comment]
平西のところ丸ごと変更
```php
Route::get('/cart', [CartController::class, 'index'])->middleware('auth');
Route::post('/cart/add', [CartController::class, 'add'])->middleware('auth');
Route::post('/cart/update', [CartController::class, 'update'])->middleware('auth');
Route::post('/cart/delete/{id}', [CartController::class, 'delete'])->middleware('auth');

Route::get('/sale/confirm', [SaleController::class, 'confirm'])->middleware('auth');
Route::get('/sale/registration_credit', [SaleController::class, 'registration_credit'])->middleware('auth');
Route::post('/sale/registration_credit', [SaleController::class, 'registration_credit_into_DB'])->middleware('auth');
Route::post('/sale/procedure', [SaleController::class, 'procedure'])->middleware('auth');
Route::get('/sale/complete', [SaleController::class, 'complete'])->middleware('auth');
```

**Comment by almex-h-hiranishi** [comment]
実質変更は最後の一行だけ
平西のルーティング
```php
// カート画面
Route::get('/cart', [CartController::class, 'index'])->middleware('auth');
Route::post('/cart/add', [CartController::class, 'add'])->middleware('auth');
Route::post('/cart/update', [CartController::class, 'update'])->middleware('auth');
Route::post('/cart/delete/{id}', [CartController::class, 'delete'])->middleware('auth');
// クレカ登録画面
Route::get('/sale/registration_credit', [SaleController::class, 'registration_credit'])->middleware('auth');
Route::post('/sale/registration_credit', [SaleController::class, 'registration_credit_into_DB'])->middleware('auth');
// 購入画面
Route::get('/sale/confirm', [SaleController::class, 'confirm'])->middleware('auth');
Route::post('/sale/procedure', [SaleController::class, 'procedure'])->middleware('auth');
Route::get('/sale/complete/{id}', [SaleController::class, 'complete'])->middleware('auth');
```

**Comment by mm-okuda** [comment]
奥田のところ変更お願いします

`Route::get('admin/product_register', [AdminController::class, 'product'])->middleware('auth');
Route::get('admin/stock_list', [adminController::class, 'stock_list'])->middleware('auth');
Route::get('admin/purchase_register', [AdminController::class, 'purchase_product'])->middleware('auth');
Route::get('admin/purchase_list', [adminController::class, 'purchase_list'])->middleware('auth');
Route::post('admin/product_register', [AdminController::class, 'product_register'])->middleware('auth');
Route::post('admin/purchase_register', [AdminController::class, 'purchase_register'])->middleware('auth');
Route::get('admin/edit_purchase/{id}', [AdminController::class, 'edit_purchase'])->middleware('auth');
Route::post('admin/edit_purchase/{id}', [AdminController::class, 'edit_purchase'])->middleware('auth');
Route::post('admin/update_purchase/{id}', [AdminController::class, 'update_purchase'])->middleware('auth');
Route::post('admin/purchase_list', [AdminController::class, 'delete_purchase'])->middleware('auth');
Route::get('admin/sale_list', [AdminController::class, 'sale_list'])->middleware('auth');
Route::post('admin/sale_list', [AdminController::class, 'sale_deliveried'])->middleware('auth');
`

**Comment by almex-h-hiranishi** [comment]
平西のルーティング
```php
// カート画面
Route::get('/cart', [CartController::class, 'index'])->middleware('auth');
Route::post('/cart/add', [CartController::class, 'add'])->middleware('auth');
Route::post('/cart/update', [CartController::class, 'update'])->middleware('auth');
Route::post('/cart/delete/{id}', [CartController::class, 'delete'])->middleware('auth');
// クレカ登録画面
Route::get('/sale/registration_credit', [SaleController::class, 'registration_credit'])->middleware('auth');
Route::post('/sale/registration_credit', [SaleController::class, 'registration_credit_into_DB'])->middleware('auth');
// 購入画面
Route::get('/sale/confirm', [SaleController::class, 'confirm'])->middleware('auth');
Route::post('/sale/procedure', [SaleController::class, 'procedure'])->middleware('auth');
Route::get('/sale/complete/{id}', [SaleController::class, 'complete'])->middleware('auth');
// 購入履歴一覧
Route::get('/sale/list', [SaleController::class, 'list'])->middleware('auth');
Route::get('/sale/list/{id}', [SaleController::class, 'detail'])->middleware('auth');
```

**Comment by mm-okuda** [comment]
//ユーザー情報、履歴画面
`Route::get('user/list', [SaleController::class, 'list'])->middleware('auth');`
`Route::get('user/edit_user', [SaleController::class, 'edit_user'])->middleware('auth');`
`Route::post('user/edit_user', [SaleController::class, 'update_user'])->middleware('auth');`

追加です

**Comment by almex-h-hiranishi** [comment]
平西のところ
```php
// カート画面
Route::get('/cart', [CartController::class, 'index'])->middleware('auth');
Route::post('/cart/add', [CartController::class, 'add'])->middleware('auth');
Route::post('/cart/update', [CartController::class, 'update'])->middleware('auth');
Route::post('/cart/delete/{id}', [CartController::class, 'delete'])->middleware('auth');
// クレカ登録画面
Route::get('/sale/registration_credit', [SaleController::class, 'registration_credit'])->middleware('auth');
Route::post('/sale/registration_credit', [SaleController::class, 'registration_credit_into_stripe'])->middleware('auth');
// 購入画面
Route::get('/sale/confirm', [SaleController::class, 'confirm'])->middleware('auth');
Route::post('/sale/procedure', [SaleController::class, 'procedure'])->middleware('auth');
Route::get('/sale/complete/{id}', [SaleController::class, 'complete'])->middleware('auth');
```

**Comment by mm-okuda** [comment]
`Route::get('admin/contact_list', [AdminController::class, 'contact_list'])->middleware('auth');`
`Route::get('admin', function(){
    return view('/admin/index');
});`
奥田のところに追加
