### ISSUE TITLE
seederファイルを作る

### ISSUE THREAD

**Issue by k-sasaki7345** [mn-honda/Usen-Studios#23]

**Comment by k-sasaki7345** [comment]
ProdutsTableSeeder、CategoriesTableSeeder作成

**Comment by mm-okuda** [comment]
SizesTableSeeder作成
PurchasesTableSeeder, StocksTableSeeder←後から必要になったときに追加

**Comment by k-sasaki7345** [comment]
SizesTableSeeder作成

**Comment by k-sasaki7345** [comment]
UsersTableSeeder作成
